AWSTemplateFormatVersion: 2010-09-09

Transform: AWS::Serverless-2016-10-31

Description: AWS Perspective DrawIo lambda stack

Parameters:

  DrawioCodeBucket:
    Type: String
    Description: The bucket where the zip files containing the source code for drawio lambda

  DeploymentBucketKey:
    Type: String
    Description: The key within the bucket that contains the source code zips

Resources:

  DrawIOExportFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: Converts cytoscape JSON to a Draw IO URL
      Runtime: python3.8
      Handler: main.handler
      CodeUri:
        Bucket: !Ref DrawioCodeBucket
        Key: !Sub ${DeploymentBucketKey}/drawio.zip
      Timeout: 5
      MemorySize: 256

  DrawioLambdaErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: Alarm if DrawIOExportFunction lambda function errors out too many times
      Namespace: AWS/Lambda
      MetricName: Errors
      Dimensions:
        - Name: FunctionName
          Value: !Ref DrawIOExportFunction
      Statistic: Sum
      ComparisonOperator: GreaterThanThreshold
      Threshold: 10
      EvaluationPeriods: 3
      Period: 60
      TreatMissingData: breaching

Outputs:

  DrawioLambdaARN:
    Description: Drawio function details
    Value: !GetAtt DrawIOExportFunction.Arn
    Export:
      Name: !Sub ${AWS::Region}-${AWS::StackName}-DrawioLambdaARN
