AWSTemplateFormatVersion: '2010-09-09'
Description: AWS Perspective - Stores api and bucket details into the parameter store.
Parameters:
  DiscoveryBucketName:
    Type: String
    Description: The Name of the bucket where all of the perspective data is stored.
  PerspectiveServerEndpoint:
    Type: String
    Description: The server API endpoints
  PerspectiveConfigurationAggregator:
    Type: String
    Description: The name of the configAggregator
  PerspectiveClusterName:
    Type: String
    Description: The name of the perspective fargate cluster
Resources:
  zoomDataBucket:
    Type: AWS::SSM::Parameter
    Properties:
      Name: zoomDataBucket
      Type: String
      Value:
        Ref: DiscoveryBucketName
      Description: Main perspective data bucket.
  zoomServerAPIEndpoint:
    Type: AWS::SSM::Parameter
    Properties:
      Name: zoomServerEndpoint
      Type: String
      Value:
        Ref: PerspectiveServerEndpoint
      Description: The perspective server endpoint.
  zoomConfigAggregatorPS:
    Type: AWS::SSM::Parameter
    Properties:
      Name: zoomConfigAggregator
      Type: String
      Value:
        Ref: PerspectiveConfigurationAggregator
      Description: The main perspective account aggregator.
  zoomECSNamePS:
    Type: AWS::SSM::Parameter
    Properties:
      Name: zoomECSName
      Type: String
      Value:
        Ref: PerspectiveClusterName
      Description: The main perspective account aggregator.
  

